Remove explicit keyword in AtomicReference constructor
It breaks compilation in GCC:
../../../chromium-86.0.4209.2/third_party/nearby/src/cpp/core_v2/internal/payload_manager.cc: In constructor 'location::nearby::connections::PayloadManager::PendingPayload::PendingPayload(std::unique_ptr<location::nearby::connections::InternalPayload>, const EndpointIds&,
 bool)':
../../../chromium-86.0.4209.2/third_party/nearby/src/cpp/core_v2/internal/payload_manager.cc:950:28: error: converting to 'location::nearby::AtomicReference<location::nearby::connections::PayloadManager::EndpointInfo::Status>' from initializer list would use explicit constructor 'location::nearby::AtomicReference<T, typename std::enable_if<((sizeof (T) <= sizeof (unsigned int)) && std::is_trivially_copyable<_Tp>::value), void>::type>::AtomicReference(T) [with T = location::nearby::connections::PayloadManager::EndpointInfo::Status; typename std::enable_if<((sizeof (T) <= sizeof (unsigned int)) && std::is_trivially_copyable<_Tp>::value), void>::type = void]'